articles/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:article_pk>/', views.detail, name='detail'),
    path('delete/<int:article_pk>', views.delete, name='delete'),
    path('<int:article_pk>/comment_create/', views.comment_create, name='comment_create'),
    path('update/<int:article_pk>', views.update, name='update'),
    path('d_delete/<int:comment_pk>', views.c_delete, name='c_delete'),
]

crud/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from django.db import models
from imagekit.models import ProcessedImageField, ImageSpecField
from imagekit.processors import ResizeToFill
# Create your models here.
# 1. 모델(스키마) 정의
# 데이터베이스 테이블을 정의하고,
# 각각의 컬럼(필드)를 정의
class Article(models.Model):
    # id : integer 자동으로 정의(Primary key)
    # id = models.AutoField(primary_key=True) -> Integer 값이 자동으로 하나씩 증가(AUTOINCREMENT)
    #CharField는 필수인자로 max_length 지정
    title = models.CharField(max_length=10)
    content = models.TextField()
    #DateTimeField
    # auto_now_add : 생성시 자동으로 입력
    # auto_now : 수정시마다 자동으로 저장
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    #image = models.ImageField(blank=True)
    #image_thumbnail = ProcessedImageField(                                                          # processedImageField 말고 imageSpecField사용 할 경우 바로 이미지 사용(컷트 후) 가능
    #     blank = True,
    #     processors = [ResizeToFill(300, 300)],
    #     format = 'JPEG',
    #     options={'quality': 60}
    # )
    image_thumbnail = ImageSpecField(
        processors = [ResizeToFill(300,300)],
        format = 'JPEG',
        options = {'QUALITY' : 80}
    )                                                   #fill vs fit 
                                                                        # fill : 300 300으로 자르기
                                                                        # fit : 긴 쪽을 기준으로 하여 비율 유지하면서 자르기
                                                                        #ProcessedImageField : Input 받은 것을 수정해 가면서 저장
    image_fit = ProcessedImageField(
        processor = [ResizeTofill(300, 300)],
        format='JPEG',
        options={'quality' : 80},
        UPLOAD_TO='fit/'
    )
    image_fill = ProcessedImageField(
        processor = [ResizeToFill(300, 300)],
        format="JPEG",
        options={'quality': 80}
        
    )
    def __str__(self):
        return f'<{self.id}> - <{self.title}>'
# models.py : python 클래스 정의
            #:모델 설계도 
# makemigrations : migration 파일 생성
#                : DB 설계도 작성
#      

class Comment(models.Model):
    content = models.CharField(max_length=140)
    created_at = models.DateTimeField(auto_now_add=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
   
   
   
    #on delete
    # 1. CASCADE : 글이 삭제되었을 때 모든 댓글 삭제
    # 2. PROTECT : 댓글이 존재하면 글 삭제 ㅏㅇㄴ됨.
    # 3. SET_NULL : 글이 삭제되면 NULL로 치환(NOT NULL일 경우 옵션 사용X)
    # 4. SET_DEFAULT : 디폴트 값으로 치환.
    #  

articles/forms.py
from django import forms
from .models import Article, Comment
class ArticleForm(forms.ModelForm):
    title = forms.CharField(
        max_length=140,
        label='제목',
        help_text='140자 이내로 작성 바랍니다.',
        widget=forms.TextInput(
            attrs={
                'placeholder': '제목을 입력바랍니다.'
            }
        )
    )    
    class Meta :
        model = Article
        fields = '__all__'
        # widgets = {
        #     'title': forms.TextInput(
        #         attrs={
        #             'placeholder': '제목을 입력바랍니다'
        #         }
        #     )
        # }
        #위젯 설정은 위에 있는 두가지 방법 모두 아무거로나 가능

class CommentForm(forms.ModelForm):
    class Meta :
        model = Comment
        exclude = ('article',)

articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Article,Comment 
from django.views.decorators.http import require_POST
from django.contrib import messages
from .forms import ArticleForm,CommentForm

# Create your views here.
def index(request):
    articles = Article.objects.all()
    context = {
        'articles' : articles
    }
    return render(request, 'articles/index.html', context)



def create(request):
    if request.method == 'POST':
        article_form = ArticleForm(request.POST,request.FILES)
        if article_form.is_valid():
            article = article_form.save()
            return redirect('articles:detail', article.pk)
    else:
        article_form = ArticleForm()
    context = {
        'article_form': article_form
    }
    return render(request, 'articles/form.html', context)


def update(request, article_pk):
    #request = POST => 검증 및 저장
    article =get_object_or_404(Article, pk=article_pk)
    if request.method == 'POST':  
        article_form = ArticleForm(request.POST, instance=article)
        if article_form.is_valid():
            #검증 성공하면 저장
            content= article_form.cleaned_data.get('content')
            article.content = content
            article.save()
            return redirect('articles:detail', article_pk)
    # request = GET => Form 전달
    else:
        article_form = ArticleForm( instance = article)
        initial = {
            'title' : article.title,
            'content' : article.content
        }
    context = {
        'article_form' : article_form
    }
    return render(request, 'articles/form.html', context)
    # GET => 비어있는 Form 전달
    # POST => 검증 실패시 에러메세지와 입력값 채워진 Form context


def delete(request, article_pk):
    article =get_object_or_404(Article, pk=article_pk)
    if request.method == 'POST':
        article.delete()
        return redirect('articles:index')
    else:
        return redirect('articles:detail', article.pk)


def detail(request, article_pk):
    article =get_object_or_404(Article, pk=article_pk)
    comment = article.comment_set.all()
    comment_form = CommentForm()
    context = {
        'article' : article,
        'comment' : comment,
        'comment_form' : comment_form
    }
    return render(request, 'articles/detail.html', context)



def comment_create(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    # 1. model.form에 사용자 입력값
    comment_form = CommentForm(request.POST)
    # 2. 검증
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.article = article
        comment.save()
    # 3. return redirect
    else:
        messages.success(request, '댓글이 형식에 맞지 않습니다')
    return redirect('articles:detail', article_pk)



    # comment = Comment()
    # comment.content = request.POST.get('comment')
    # comment.article_id= article_pk
    # comment.save()
    # messages.add_message(request, messages.INFO, '등록되었습니다')
    # return redirect('articles:detail', article_pk)


def c_delete(request, comment_pk):
    comment = Comment.objects.get(id=comment_pk)
    article_pk = comment.article_id
    comment.delete()
    messages.add_message(request, messages.WARNING, '삭제되었습니다')
    return redirect('articles:detail', article_pk)

articles/templates/articles/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>게시판</title>
  <link rel='stylesheet'href = "{% static 'bootstrap/css/bootstrap.min.css' %}">
  {% block css %}
  <link rel = 'stylesheet' href = '{% static 'articles/style.css' %}'>
  {% endblock %}
</head>
<body>
  <!-- 여기에 message 구현할 경우, base를 extend 한
     모든 html파일에서 메세지 사용 가능! 
  -->
  {% block body %}
  {% endblock %}
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

articles/templates/articles/create.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
  <h1>{{data.id}}번째 게시글 저장 완료 되었습니다.</h1>
  <a href="{% url 'articles:index' %}">확인하기</a>

</body>
</html>

articles/templates/articles/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <title>Document</title>
</head>
<body>
  {% if messages %}
  {% for message in messages%}
    <div class="alert alert-primary" role = "alert"><h5>{{message.message}}</h5></div>
  {% endfor %}
  {% endif %}
  <label for='title'>제목:</label><br>
  <p id = 'title'>
    {{article.title}}
  </p><br>
  <label for='c_time'>작성시간</label>
  <p id='c_time'>
    {{article.created_at}}
  </p><br>
  <label for='u_time'>수정일자</label>
  <p id='u_time'>
    {{article.updated_at}}
  </p><hr>
  <label for='content'>내용</label><br>
  <p id='content'>
    {{article.content}}</p>
  <label for ='image'>이미지</label><br>
  <img src='{{article.image.url}}' alt="{{article.image.name}}">
  <br>

  <a href='{% url 'articles:index' %}'><button>돌아가기</button></a>
  <form action='{% url 'articles:delete' article.pk %}' method = 'POST'>
    {% csrf_token %}
    <input type='submit' value='삭제''>
    </form>
  <a href='{% url 'articles:update' article.pk %}'><button>수정</button></a>
  <div>
    <h1>--댓글-- {{comment.count}}개</h1>
    {% for comment_a in comment %}
    <h4>{{comment_a.content}}</h2>
    <a href='{% url 'articles:c_delete' comment_a.pk %}'>삭제</a>
    <hr>
    {% empty %}
    <h1>댓글을 입력해주세요!</h1>
    {% endfor %}
    
    <!-- {% for comment in article.comment_set.all %}
    <li>{{ comment.content }} </li>
    <li>{{ comment.created_at }} </li>
    <br>
    {% endfor %} -->
  </div>
  <form action="/articles/{{article.pk}}/comment_create/" method="POST">
    {% csrf_token %}
    {{ comment_form.as_p }}
    <input type = 'submit' value='등록'>
  </form>
  






  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

articles/templates/articles/form.html
<!DOCTYPE html>
<html lang="en">
  {% extends 'articles/base.html' %}
  {% block body %}
  {% load bootstrap4 %}

  {% if request.resolver_match.url_name == 'create' %}
  <h1 class="text-center"> 글 생성하기 </h1>
  {% else %}
  <h1 class='text-center'> 글 수정하기</h1>
  {% endif%}
  <form acction='' method="post" class='form' enctype='multipart/form-data'>
    {% csrf_token %}
    {% bootstrap_form article_form %}
    {% buttons %}
    <button type="submit" class="btn btn-primary"> Submit</button>
    {% endbuttons %}
  </form>
{% endblock%}
</html>

articles/templates/articles/index.html
{% extends 'articles/base.html' %}
{% load static %}

<!-- <!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>게시</title> -->
 
  {% block css %}
  <style>
  td, th  {
    border: 1px dotted black;
    text-align:center;
  }
  </style>
  {% endblock %}
<!--<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head> -->
  {% block body %}
  <nav class="navbar navbar-expand-lg navbar-light bg-info">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>
  <h1 class='d-flex justify-content-center'>게시판에 오신걸 환영합니다.</h1>
  <a href="create" class='btn d-inline-flex btn-warning m-3'>글 작성하기</a>

  <table class="table mt-3">
      <thead>
        <tr>
          <th scope="col" class='text-center'>게시판 번호</th>
          <th scope="col" class='text-center'>제목</th>
          <th scope="col"class='text-center'>내용</th>
          <th scope="col"class='text-center'>작성일자</th>
          <th scole="col"class='text-center'></th>
        </tr>
      </thead>  
      <tbody>
        {% for A in articles %}
        <tr>
          <th scope="row" class='text-center'>{{A.id}}</th>
          <td class='text-center'>{{A.title}}</td>
          <td class='text-center'>{{A.content}}</td>
          <td class='text-center'>{{A.created_at}}</td>
          <td class='text-center'><a href='{{A.id}}'>내용 보기</a></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>




  <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script> -->
{% endblock %}

articles/templates/articles/new.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-info">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Dropdown
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>
  <!-- <form action='/articles/create'>
    <div>
    <label for="t_input">제목</label>
    <input type="text", id="title", name="title"></div>
    <div>
    <label for="c_input">내용</label>
    <textarea id="c_input", name="content"></textarea>
  </div>
    <input type="submit", value="제출하기">
  </form> -->
  
  <form action='' method = 'POST'>
    {% csrf_token %}
    {{article_form.as_p}}
    <button type="submit" class="btn btn-success">글 쓰기</button>
    </form>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

articles/templates/articles/new2.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-info">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Dropdown
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>
  <!-- <form action='/articles/create'>
    <div>
    <label for="t_input">제목</label>
    <input type="text", id="title", name="title"></div>
    <div>
    <label for="c_input">내용</label>
    <textarea id="c_input", name="content"></textarea>
  </div>
    <input type="submit", value="제출하기">
  </form> -->
  <form action="{% url "articles:create" %}" method = 'post' style="height:500px">
    {% csrf_token %}
    <div class="form-group" style="height:200px">
      <label for="exampleInputTitle">제목</label>
      <input type="text" class="form-control h-25" id="exampleInputTitle" name='title'>
    </div>
    <div class="form-group" style="height:250px">
      <label for="exampleInputContents">내용</label>
      <input type="text" class="form-control h-50" id="exampleInputContents" name='content'>
    </div>
    <button type="submit" class="btn btn-success">글 쓰기</button>
  </form>
  <form action='' method = 'POST'>
    {% csrf_token %}
    {{article_form.as_p}}
    <button type="submit" class="btn btn-success">글 쓰기</button>
    </form>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

articles/templates/articles/update.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>

   
    <form action='' method='POST'>
      {% csrf_token %}
      {{article_form.as_p}}
      <button type="submit" class="btn btn-success">글 쓰기</button>
    </form>
</body>
</html>